name: 📱 slack

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '0 12 * * *'  # runs every day at 12:00 UTC

jobs:
  scrape-android-reports:
    runs-on: ubuntu-latest

    steps:

    - name: Postd blocks to a Slack channel
      run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' 
                 ${{secrets.WEBHOOK_URL)
